export const CREATE_PASSWORD_SUCCESS= 'CREATE_PASSWORD_SUCCESS'

export const UPDATE_PASSWORD_SUCCESS= 'UPDATE_PASSWORD_SUCCESS'

export const DELETE_PASSWORD_SUCCESS= 'DELETE_PASSWORD_SUCCESS'

export const FETCH_PASSWORD_SUCCESS= 'FETCH_PASSWORD_SUCCESS'